### ISSUE TITLE
PLS and O-PLS has not the format for cross-validation package

### ISSUE THREAD

**Issue by jobo322** [mljs/pls#13]
I mean into [cross-validation](https://github.com/mljs/cross-validation), the function [validate](https://github.com/mljs/cross-validation/blob/master/src/index.js) try to initialize the classifier with classifierOptions but PLS construtor does not work thus. what do you think about modify PLS package to make compatible with cross-validation?

**Comment by maasencioh** [comment]
it should be done, maybe @JeffersonH44 could help you, but if you could do it that will be great
