### ISSUE TITLE
convert dataset to matrix if not matrix

### ISSUE THREAD

**Issue by lpatiny** [mljs/pls#18]
Add a testcase with array of array as dataset

Use a similar code to ensure it is a matrix in the constructor

https://github.com/mljs/pca/blob/master/src/pca.js#L29

**Comment by targos** [comment]
You need to be more specific on what the problem is because currently `Matrix.checkMatrix()` is called on the dataset: https://github.com/mljs/pls/blob/e64c0906fdcffbf27d6d81871987f13c3e2666b5/src/PLS.js#L51-L52
