### ISSUE TITLE
How to save and load a OPLS model with nodejs? 

### ISSUE THREAD

**Issue by JiayiHong** [mljs/pls#32]
Hello,

I have trouble saving and loading the OPLS model.  I tried to load a OPLS model with `PLS.OPLS.load(obj)` but it has an error like the below:
`OPLS.js:355 Uncaught (in promise) TypeError: model.wOrth.transpose is not a function in OPLS.js:355.`
My codes are like below:
`const model = pls.toJSON();
  exportJsonFile("pls", model);

  const obj = await fetchJson('pls.json');
  const pls = PLS.OPLS.load(obj);
  const result = pls.predict(testSetx, { trueLabels:testSety});`

Thank you so much in advance!

**Comment by targos** [comment]
It's probably a bug. You code seems correct.
