### ISSUE TITLE
Documentation is empty

### ISSUE THREAD

**Issue by targos** [mljs/pls#42]
http://mljs.github.io/pls/

Maybe a problem with the new version of https://github.com/zakodium/documentationjs-action

**Comment by santimirandarp** [comment]
> http://mljs.github.io/pls/
> 
> Maybe a problem with the new version of https://github.com/zakodium/documentationjs-action

It seems that the docs folder isn't in the GH pages branch. Could it be that we need `.` instead of `docs` in the documentationjs workflow? I'll check from my notebook later

Same happens here:
 https://mljs.github.io/levenberg-marquardt/
